name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - uses: s-weigand/setup-conda@v1
    # need to watch vtk + mayavi wheels to be sure python version is supported

    - run: conda install mayavi
    - run: pip install -e .[tests,lint]

    - run: flake8
    - run: mypy

    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: pytest
